/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "wrapper.go"

struct node_info {
    char* Name;
    char* Version;
    char* Addr;
    int State;
    int ConnState;
    long long Delay;
    long long OnlineTs;
    long long OfflineTs;
    long long ActiveTs;
    long long BrainTs;
};

struct brain_info {
    char* Name;
    char* Version;
    char* Addr;
};

struct node_status {
    char* Name;
    char* Platform;
    int CpuCores;
    long long LocalTime;
    double CpuLoadShort;
    double CpuLoadLong;
    long long MemUsed;
    long long MemTotal;
    long long DiskUsed;
    long long DiskTotal;
};

struct execution_result {
    char* Name;
    int Code;
    char* CommunicationErrorMsg;
    char* ProcessErrorMsg;
    char* Result;
};

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/* Return type for Init */
struct Init_return {
	int r0;
	char* r1;
};
extern struct Init_return Init(GoString configFile);

/* Return type for NodeInfo */
struct NodeInfo_return {
	int r0;
	char* r1;
};
extern struct NodeInfo_return NodeInfo(GoSlice names, struct brain_info* brain, GoSlice results, int* size);

/* Return type for NodeStatus */
struct NodeStatus_return {
	int r0;
	char* r1;
};
extern struct NodeStatus_return NodeStatus(GoSlice names, GoSlice results, int* size);

/* Return type for UploadFile */
struct UploadFile_return {
	int r0;
	char* r1;
};
extern struct UploadFile_return UploadFile(GoString localFileOrDir, GoString remoteTargetPath, GoUint8 isForce, GoSlice names, GoSlice results, int* size);

/* Return type for DownloadFile */
struct DownloadFile_return {
	int r0;
	char* r1;
};
extern struct DownloadFile_return DownloadFile(GoString remoteFileOrDir, GoString localTargetPath, GoString name, struct execution_result* result);

/* Return type for RunCommand */
struct RunCommand_return {
	int r0;
	char* r1;
};
extern struct RunCommand_return RunCommand(GoString cmd, GoUint8 needAlign, GoSlice names, GoSlice results, int* size);

/* Return type for RunScript */
struct RunScript_return {
	int r0;
	char* r1;
};
extern struct RunScript_return RunScript(GoString cmd, GoUint8 needAlign, GoSlice names, GoSlice results, int* size);

/* Return type for RunCommandBackground */
struct RunCommandBackground_return {
	int r0;
	char* r1;
};
extern struct RunCommandBackground_return RunCommandBackground(GoString cmd, GoUint8 needAlign, GoSlice names, GoSlice results, int* size);

/* Return type for XRunCommand */
struct XRunCommand_return {
	int r0;
	char* r1;
};
extern struct XRunCommand_return XRunCommand(GoString cmd, GoUint8 needAlign, GoInt delay, GoSlice names, GoSlice results, int* size);

/* Return type for XRunScript */
struct XRunScript_return {
	int r0;
	char* r1;
};
extern struct XRunScript_return XRunScript(GoString cmd, GoUint8 needAlign, GoInt delay, GoSlice names, GoSlice results, int* size);

/* Return type for ScenarioInfo */
struct ScenarioInfo_return {
	char* r0;
	int r1;
	char* r2;
};
extern struct ScenarioInfo_return ScenarioInfo(GoString name);

/* Return type for ScenariosInfo */
struct ScenariosInfo_return {
	int r0;
	char* r1;
};
extern struct ScenariosInfo_return ScenariosInfo(GoSlice results, int* size);

/* Return type for ScenarioVersion */
struct ScenarioVersion_return {
	char* r0;
	int r1;
	char* r2;
};
extern struct ScenarioVersion_return ScenarioVersion(GoString name, GoInt offset, GoInt limit);

/* Return type for NodeAppInfo */
struct NodeAppInfo_return {
	char* r0;
	int r1;
	char* r2;
};
extern struct NodeAppInfo_return NodeAppInfo(GoString name, GoString app, GoString scenario);

/* Return type for NodeAppsInfo */
struct NodeAppsInfo_return {
	int r0;
	char* r1;
};
extern struct NodeAppsInfo_return NodeAppsInfo(GoString name, GoSlice results, int* size);

/* Return type for Apply */
struct Apply_return {
	int r0;
	char* r1;
};
extern struct Apply_return Apply(GoString deployment, GoString target, GoString message, GoInt timeout, GoSlice logs, int* size);

#ifdef __cplusplus
}
#endif
