worker:
  id: 0
  name: "pi0"
  ip: "127.0.0.1"
  port: 23456
ssh:
  username: "pi"
  password: "network123"
  port: 22
master:
  ip: "127.0.0.1"
  port: 3456
  token: "default"
logger:
  path: "/root/platform"
  namePrefix: "log"
  rollDays: 3
heartbeat:
  sendInterval: 1
  reconnectInterval: 10
  retryTime: 6
  autoRestart: false
workspace:
  root: "/root/workspace/"
  
